### ISSUE TITLE
Protecting private data from forked repositories

### ISSUE THREAD

**Issue by EKami** [argoflow/argoflow-aws#140]
I'm not very fluent with argocd but the way I understand it some applications rely on the github repo to pull the Kustomize scripts instead of using the scripts locally, and that's not really convenient to keep the data private.

Let me illustrate what I want to say with an example.
Lets take the `distribution/argocd-applications/istio.yaml`  app, the k8s CRD definition is this:
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: <<__git_repo.url__>>
    targetRevision: <<__git_repo.target_revision__>>
    path: distribution/istio
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

where `<<__git_repo.url__>>` and `<<__git_repo.target_revision__>>`  are pointing to my public fork. When deployed to a cluster argocd will fetch the kustomize scripts from `distribution/istio` on my branch. 

The problem is: What is on the github doesn't have the variable replacement that I have locally. For instance if I go to my branch and find `distribution/istio/istio-spec.yaml`, instead of finding the definition with the vars replaced I will find something like this:
```
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
  name: istio
spec:
  profile: default
  tag: 1.10.1 # istio/operator
  hub: docker.io/istio
  meshConfig:
    accessLogFile: /dev/stdout
    enablePrometheusMerge: true
    extensionProviders:
    - name: oauth2-proxy
      envoyExtAuthzHttp:
        service: oauth2-proxy.auth.svc.cluster.local
        port: '4180' # The default port used by oauth2-proxy.
        #includeHeadersInCheck: ["authorization", "cookie"]  # headers sent to the oauth2-proxy in the check request.
        includeHeadersInCheck: # headers sent to the oauth2-proxy in the check request.
            # https://github.com/oauth2-proxy/oauth2-proxy/issues/350#issuecomment-576949334
        - cookie
        - x-forwarded-access-token
        - x-forwarded-user
        - x-forwarded-email
        - authorization
        - x-forwarded-proto
        - proxy-authorization
        - user-agent
        - x-forwarded-host
        - from
        - x-forwarded-for
        - accept
        headersToUpstreamOnAllow: [authorization, path, x-auth-request-user, x-auth-request-email, x-auth-request-access-token, x-auth-request-user-groups]             # headers sent to backend application when request is allowed.
        headersToDownstreamOnDeny: [content-type, set-cookie]     # headers sent back to the client when request is denied.
  components:
    ingressGateways:
    - name: istio-ingressgateway
      k8s:
        service:
          type: LoadBalancer
        serviceAnnotations:
          service.beta.kubernetes.io/aws-load-balancer-name: <<__aws_load_balancer.name__>>
          # service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "3"
          # service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
          # service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
          #service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "HTTP"
          #service.beta.kubernetes.io/aws-load-balancer-healthcheck-port: "15021"
          #service.beta.kubernetes.io/aws-load-balancer-healthcheck-path
          service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'
          service.beta.kubernetes.io/aws-load-balancer-scheme: <<__aws_load_balancer.scheme__>>
          service.beta.kubernetes.io/aws-load-balancer-type: external
          service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: <<__aws_load_balancer.nlb_target_type__>>
          proxy.istio.io/config: '{"gatewayTopology" : { "numTrustedProxies": 2 } }'
          external-dns.alpha.kubernetes.io/hostname: <<__route53.hosted_zone_hostnames__>>
  values:
    sidecarInjectorWebhook:
      neverInjectSelector:
      # kube-prometheus-stack
      ## Admission Webhook jobs do not terminate as expected with istio-proxy
      - matchExpressions:
        - {key: app, operator: In, values: [kube-prometheus-stack-admission-create, kube-prometheus-stack-admission-patch]}
```
`<<__aws_load_balancer.scheme__>>`/`<<__aws_load_balancer.nlb_target_type__>>`... will not be replaced.
The reason is simply because I use this script to replace the vars:

```
argoflow_tmp=/tmp/argoflow

echo "Installing argoflow..."
rm -rf $argoflow_tmp
mkdir -p $argoflow_tmp
cp -fR $DIR/distribution $argoflow_tmp
cp $DIR/setup_repo.sh $argoflow_tmp
cp $DIR/setup.conf $argoflow_tmp
cp $DIR/setup_credentials.sh $argoflow_tmp

cd $argoflow_tmp
echo "Replace vars in kustomize file..."
./setup_repo.sh ./setup.conf
echo "Running kustomize..."
kustomize build distribution/external-secrets/ | kubectl apply -f -
kustomize build distribution/argocd/base/ | kubectl apply -f -
kustomize build distribution/ | kubectl apply -f -
```

where all the vars are replaced in a local folder in `/tmp/argoflow`, **that's something that I will NEVER commit to a public github repo since it's sensitive data**.

The solution would be to remove `<<__git_repo.url__>>` and `<<__git_repo.target_revision__>>` completely and instead of relying on the manifests from github, argocd should use the local ones directly. Something like this (it's incorrect but you guys get the idea):
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    localPath: distribution/istio
    kustomize:
      version: v4.0.5
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
```

Notice the `localPath`
I dunno if something like this is possible with argocd, I'll do some research but my knowledge of k8s and argocd are pretty limited.

Another solution would be to avoid using the `<< . >>` vars in the app manifests, and rely on k8s ConfigMaps that are set/replaced before deploying the argocd apps with `kustomize build distribution/ | kubectl apply -f -`
