### ISSUE TITLE
[Clusterrole] External Secrets permission error

### ISSUE THREAD

**Issue by jaystary** [argoflow/argoflow-aws#219]
With the specified policy after the rollout we get an error in fetching external secrets from AWS Secretsmanager as it wants a **get** on that API group.

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets
  labels:
    name: kubernetes-external-secrets
rules:
- apiGroups: ['']
  resources: [secrets]
  verbs: [create, update]
```

When adding the **get**, it works without issue. 
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-secrets
  labels:
    name: kubernetes-external-secrets
rules:
- apiGroups: ['']
  resources: [secrets]
  verbs: [get, create, update]
```

What i find strange though is the fact that [create, update] was there originally and previously we still had succesful rollouts. Is there an issue with just adding the **get** to the permission? If no i would like to integrate that.
